name: Build Windows EXE
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: gcc cycraft-windows.c -o cycraft_emu.exe -lws2_32
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: cycraft-emulator-exe
          path: cycraft_emu.exe
